apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: velib-insights

build:
  local:
    push: false   # Important pour le dev local sans registre distant
  artifacts:
    # --- Backend Express ---
    - image: yanisble/velib-insights-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          # Synchronise tout le dossier src vers le dossier /app/src du container
          - src: "src/**/*.ts"
            dest: .

    # --- Frontend React ---
    - image: yanisble/velib-insights-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.tsx'
            dest: .
          - src: 'index.html'
            dest: .

deploy:
  kubectl:
    manifests:
      - ./infra/local-dev-k8s/*.yaml

profiles:
  - name: push
    build:
      local:
        push: true